repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: debug-statements
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        args: [--preview]  # More aggressive line breaking

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-PyYAML',
            'sqlalchemy-stubs',
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: local
    hooks:
    -   id: docformatter
        name: docformatter
        description: 'Formats docstrings to follow PEP 257'
        entry: docformatter
        args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88]
        language: python
        types: [python]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [
            --remove-all-unused-imports,
            --remove-unused-variables,
            --in-place
        ]
